development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: sample_development
  pool: 5

test: &test
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
  encoding: utf8

cucumber:
  <<: *test

